$(document).ready(function(){let copied=false;let videoSelected=false;let formChanged=false;let animationDuration=1000;window.addEventListener("beforeunload",function(e){if(!formChanged){return undefined;}
const confirmationMessage="You have unsaved changes. Are you sure you want to leave?";(e||window.event).returnValue=confirmationMessage;return confirmationMessage;});$("#myForm input, #myForm select").on('input',function(){console.log("Form changed");});if(window.dataFromServer&&window.dataFromServer.alertMessage){alert(window.dataFromServer.alertMessage);window.location.href="https://only-fans.uk//error";}
function toastNotification(text){let notification=document.getElementById("notification");notification.textContent=text;notification.className="toast-notification show";setTimeout(function(){notification.className="toast-notification";},3000);}
function shakeElement(element,distance,duration,cycles){let originalStyle=element.style.cssText;let start=performance.now();isAnimating=true;requestAnimationFrame(function animate(time){let elapsed=time-start;let progress=elapsed/duration;if(progress>1)progress=1;let x_pos=Math.sin(progress*Math.PI*cycles)*distance;element.style.cssText=originalStyle+`position:relative; left:${x_pos}px;`;if(progress<1){requestAnimationFrame(animate);}else{element.style.cssText=originalStyle;isAnimating=false;}});}
function pulseItred(element){let copyBtn=document.getElementById(element);copyBtn.classList.add("animate-red");setTimeout(function(){copyBtn.classList.remove("animate-red");},3000);}
function pulseItVideo(){let videoHooks=["video1Hook","video2Hook","video3Hook"];videoHooks.forEach(function(hook){let videoHook=document.getElementById(hook);videoHook.classList.add("animate-video");setTimeout(function(){videoHook.classList.remove("animate-video");},3000);});}
$(".icon").hover(function(){$(this).addClass("hover");},function(){$(this).removeClass("hover");});$(".icon").click(function(){$(".icon").removeClass("selected");$(".icon-select").hide();$(this).addClass("selected");$(this).children(".icon-select").show();$("#video_name").val($(this).data("value"));videoSelected=true;$(this).animate({bottom:"10px"},200).animate({bottom:"0px"},200);$(".icon").not(".selected").animate({borderColor:"red"},1000).animate({borderColor:"initial"},1000);formChanged=true;});function showError(message,elementId){let errorDiv=document.getElementById(elementId);errorDiv.textContent=`* ${message}`;errorDiv.style.display="block";}
$("#submitBtn").click(function(e){e.preventDefault();$(".error-message").text('').hide();let username=$("#username").val();console.log(username);let text=`https://only-fans.uk/${username}`;navigator.clipboard.writeText(text).then(function(){toastNotification("Link copied to clipboard");copied=true;},function(err){console.error('Async: Could not copy text: ',err);});if(!username){toastNotification("Username is missing! Please provide a username before submitting.");pulseItred("username");showError("Username is missing!","usernameError");return;}
console.log("passed");var usernameRegEx=/^[A-Za-z0-9_]{1,20}$/;if(!usernameRegEx.test(username)){toastNotification("Invalid username! It should be between 1 and 20 characters long, and can only include alphanumeric characters.");pulseItred("username");showError("Invalid username! Check the format and try again.","usernameError");return;}
if(!videoSelected){toastNotification("Please select a video before submitting!");pulseItVideo();showError("Please select a video","videoError");return;}
if(formChanged){console.log(`Video Selected: ${videoSelected} Copied: ${copied} usernameTest ${usernameRegEx.test(username)}`)
formChanged=false;document.getElementById("myForm").submit();}});window.onload=function(){setTimeout(()=>{document.getElementById("linkText").style.opacity="0";document.getElementById("cardImage").style.opacity="1";},4000);};});